# from galaxy
- src: geerlingguy.swap
- src: geerlingguy.ntp

# from GitHub
- src: https://github.com/ketsapiwiq/wazuh-ansible
# see also apolloclark repo
- src: https://github.com/shamsalmon/ansible-role-osquery
# For Windows
- src: https://github.com/juju4/ansible-win-osquery