---
- hosts: wazuh_agent_win_local
  pre_tasks:
    - name: debug manager IP
      debug:
        msg: "{{wazuh_manager_ip}}" 

  roles:
    - roles/wazuh-ansible/roles/wazuh/ansible-wazuh-agent
    - ansible-role-osquery

  tasks:
    - name: Enable powershell command logging
      win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows\PowerShell\ScriptBlockLogging
        name: EnableScriptBlockLogging
        data: 1
        type: dword

  vars:
      wazuh_manager_ip: "{{ groups.wazuh_manager_local[0] }}"
      wazuh_managers:
        - address: "{{ wazuh_manager_ip }}"
          port: 1514
          protocol: udp
          api_port: 55000
          api_proto: "http"
          api_user: foo
          api_pass: bar
      wazuh_agent_authd:
        # authd_pass: 'foobar'
        registration_address: "{{ wazuh_manager_ip }}"
        enable: true
        port: 1515
        ssl_agent_ca: null
        ssl_auto_negotiate: "no"
        ssl_agent_cert: null
      # wazuh_agent_config:

### OSQUERY
# TODO: Install osquery
# Wazuh OSquery config
    # osquery:
    # disable: 'no'
    # run_daemon: 'yes'
    # bin_path_win: 'C:\Program Files\osquery\osqueryd'
    # log_path_win: 'C:\Program Files\osquery\log\osqueryd.results.log'
    # config_path_win: 'C:\Program Files\osquery\osquery.conf'
    # add_labels: 'yes'


# OSQuery Role
# merge strategy required

  # osquery_config:
  #     options:
  #       config_plugin: filesystem
  #       logger_plugin: filesystem
  #       utc: 'true'
  #     schedule:
  #       system_info:
  #         query: SELECT hostname, cpu_brand, physical_memory FROM system_info;
  #         interval: 3600
  #       high_load_average:
  #         query: SELECT period, average, '70%' AS 'threshold' FROM load_average WHERE period
  #           = '15m' AND average > '0.7';
  #         interval: 900
  #         description: Report if load charge is over 70 percent.
  #       low_free_memory:
  #         query: SELECT memory_total, memory_free, CAST(memory_free AS real) / memory_total
  #           AS memory_free_perc, '10%' AS threshold FROM memory_info WHERE memory_free_perc
  #           < 0.1;
  #         interval: 1800
  #         description: Free RAM is under 10%.

      # packs:
      #   osquery-monitoring: "/usr/share/osquery/packs/osquery-monitoring.conf"
      #   incident-response: "/usr/share/osquery/packs/incident-response.conf"
      #   it-compliance: "/usr/share/osquery/packs/it-compliance.conf"
      #   vuln-management: "/usr/share/osquery/packs/vuln-management.conf"
      #   hardware-monitoring: "/usr/share/osquery/packs/hardware-monitoring.conf"
      #   ossec-rootkit: "/usr/share/osquery/packs/ossec-rootkit.conf"
