---
- hosts: wazuh_agent_win
  pre_tasks:
    # - name: debug manager IP
    # debug:
    # msg: "{{wazuh_manager_ip}}"
    - name: show ossec conf templating results
      debug:
        msg: "{{ lookup('template', './roles/wazuh-ansible/roles/wazuh/ansible-wazuh-agent/templates/var-ossec-etc-ossec-agent.conf.j2') }}"

  roles:
    - roles/wazuh-ansible/roles/wazuh/ansible-wazuh-agent
    - ansible-win-osquery

  tasks:
    - name: Enable powershell command logging
      win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows\PowerShell\ScriptBlockLogging
        name: EnableScriptBlockLogging
        data: 1
        type: dword
    - name: Enable module logging for powershell command logging
      win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows\PowerShell\ModuleLogging
        name: EnableModuleLogging
        data: 1
        type: dword
    - name: Enable module logging for powershell command logging
      win_regedit:
        path: HKLM:\Software\Policies\Microsoft\Windows\PowerShell\ModuleLogging
        name: ModuleNames
        # path: HKLM:\Software\Policies\Microsoft\Windows\PowerShell\ModuleLogging\ModuleNames
        # name: '*'
        data: '*'
        type: string
    - name: Enable powershell command transcription
      win_regedit:
        path: HKLM:\SOFTWARE\Wow6432Node\Policies\Microsoft\Windows\PowerShell\Transcription
        name: EnableTranscripting
        data: 1
        type: dword
    - name: Enable powershell command with header
      win_regedit:
        path: HKLM:\SOFTWARE\Wow6432Node\Policies\Microsoft\Windows\PowerShell\Transcription
        name: EnableInvocationHeader
        data: 1
        type: dword
    - name: set powershell command transcription directory
      win_regedit:
        path: HKLM:\SOFTWARE\Wow6432Node\Policies\Microsoft\Windows\PowerShell\Transcription
        name: OutputDirectory
        data: ''
        type: string

  vars:
    wazuh_manager_ip: "{{ groups.wazuh_manager[0] }}"
    wazuh_managers:
      - address: "{{ wazuh_manager_ip }}"
        port: 1514
        protocol: udp
        api_port: 55000
        api_proto: "http"
        api_user: foo
        api_pass: bar
    wazuh_agent_authd:
      # authd_pass: 'foobar'
      registration_address: "{{ wazuh_manager_ip }}"
      enable: true
      port: 1515
      ssl_agent_ca: null
      ssl_auto_negotiate: "no"
      ssl_agent_cert: null
    wazuh_agent_config:
      syscollector:
        disable: 'no'
        os: 'yes'
        # Needed for windows
        win_hotfixes: 'yes'
        interval: 10m
### OSQUERY
# Wazuh OSquery config
      osquery:
        disable: 'no'
        run_daemon: 'yes'
        bin_path_win: 'C:\Program Files\osquery\osqueryd'
        log_path_win: 'C:\Program Files\osquery\log\osqueryd.results.log'
        config_path_win: 'C:\Program Files\osquery\osquery.conf'
        add_labels: 'yes'

# Sysmon events
      localfiles:
        windows:
        - format: 'eventchannel'
          location: 'Microsoft-Windows-Sysmon/Operational'
# https://documentation.wazuh.com/3.9/user-manual/capabilities/log-data-collection/how-to-collect-wlogs.html

# OSQuery Role
# See roles/ansible-win-osquery/defaults/main.yml
# And config given by wazuh (originally json)