- hosts: win_agent

  roles:
    - name: wazuh-ansible/roles/wazuh/ansible-wazuh-agent
      tags:
        - wazuh
        - windows
    - name: ansible-win-osquery
      tags:
        - osquery
        - windows
    - name: win-filebeat-osquery
      tags:
        - osquery
        - windows
        - filebeat

  vars_files:
    - wazuh-agent-win-vars.yml
    - osquery-win-vars.yml

  tasks:
    - name: import extra tasks
      import_tasks: win-client-extra.yml
      tags:
        - extra
