- hosts: win_agent

  roles:
    - name: wazuh-ansible/roles/wazuh/ansible-wazuh-agent
      tags: wazuh
    - name: juju4.win-osquery
      tags: osquery

  vars_files:
    - wazuh-agent-win-vars.yml
    - osquery-win-vars.yml

  tasks:
    - name: import filebeat osquery tasks
      import_tasks: win-filebeat-osquery.yml
      tags:
        - filebeat
        - osquery

    - name: import extra tasks
      import_tasks: win-client-extra.yml
      tags: extra
