# - hosts: win_agent
#   vars:
#   tasks:
- name: Ensure filebeat is installed
  win_chocolatey:
    name: filebeat-oss
    version: "{{filebeat_version}}"
    state: present
  vars:
    # collaterate victim of the elastic / amazon war
    # https://github.com/elastic/beats/issues/25865
    filebeat_version: 7.12.0

# Invoke-WebRequest -Uri https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.15.2-windows-x86_64.zip -OutFile 'C:\Program Files (x86)\Filebeat' -UseBasicParsing
# - name: Enshure {{filebeat_config_dir}} exists
#   win_file: path={{filebeat_config_dir}} state=directory
- name: Ensure main filebeat.yml is generated
  win_template:
    src: win-filebeat.yml.j2
    dest: C:\ProgramData\Elastic\Beats\filebeat\filebeat.yml
  # notify: filebeat restart

- name: Copy osquery filebeat module config
  win_template:
    src: win-filebeat-osquery.yml.j2
    dest: C:\ProgramData\Elastic\Beats\filebeat\modules.d\osquery.yml
  # notify: filebeat restart

# FIXME: # .\filebeat.exe setup --dashboards --path.config=C:\ProgramData\Elastic\Beats\filebeat
# Loaded dashboards

- name: Ensure filebeat service is started
  win_service: name=filebeat start_mode=auto state=restarted
